name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile

  quality-control:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Find problematic patterns in code
        run: yarn run lint

  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests coverage
        run: yarn run test

  build-release:
    needs:
      - build
      - quality-control
      - unit-test
    runs-on: ubuntu-latest
    steps:
      - name: Run build --release
        run: yarn run build --release
