name: Node.js CI

x-common:
  &default-common
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x


#x-yarn-cache:
#  &-yarn-cache
#  - name: Get yarn cache directory path
#    id: yarn-cache-dir-path
#    run: echo "::set-output name=dir::$(yarn cache dir)"
#
#  - uses: actions/cache@v1
#    id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
#    with:
#      path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#      restore-keys: |
#        ${{ runner.os }}-yarn-


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    <<: *default-common



#    steps:
#
#      - name: Install dependencies
#        run: yarn --frozen-lockfile
#
#      - name: Find problematic patterns in code
#        run: yarn run lint
#
#      - name: Run unit tests coverage
#        run: yarn run test
#
#      - name: Run build --release
#        run: yarn run build --release
